src/Plans/urls.py
from django.urls import path

from .views import PlanSelectView, paymentView, updateTransaction, profileView, cancleSub

app_name = 'Plans'

urlpatterns = [
    path('', PlanSelectView.as_view(), name='plan_list'),
    path('payment/', paymentView, name='payment'),
    path('update-transactions/<subscription_id>/', updateTransaction, name='update-transactions' ), 
    path('profile/', profileView, name='profile'),
    path('cancel/', cancleSub, name="cancel")
]

src/video_sub_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Series.urls', namespace='Series')),
    path('plans/', include('Plans.urls', namespace='Plans')),

]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/snippets/messages.html
{% if messages %}

	<style type="text/css">
		div.messages{
			background-color: #ff6b6b
			color: #f7fff7;
		}
		ul.messages{
			list-style-type: none;
		}
	</style>

	<div class="messages">
		
		<ul class="messages">
			{% for message in messages %}
			<li {% if message.tags %} class="{{message.tags}}"{% endif %}> {% if "html_safe" in message.tags %}{{message|safe}}{% else %}{{ message }}{% endif %}</li>
			{% endfor%}
		</ul>
	</div>
{% endif %}

src/templates/snippets/navbar.html
<nav>
    <div class="container">
    <ol class='breadcrumb'>
          <li><a href="/">Home</a></li>
          <li><a href="{% url 'Plans:profile' %}">Profile</a></li>
          
          {% block post_detail_link %}
          {% endblock %}

          {% if not request.user.is_authenticated %}
          <li class='pull-right'><a href='/register'>Register</a></li>
          <li class='pull-right'><a href='/login'>Login</a></li>
          {% else %}
          <li class='pull-right'><a  href="/plans/">Plans</a></li>
          {% endif %}
      </ol>
  </div>
</nav>