src/Plans/urls.py
from django.urls import path

from .views import PlanSelectView, paymentView, updateTransaction, profileView, cancleSub

app_name = 'Plans'

urlpatterns = [
    path('', PlanSelectView.as_view(), name='plan_list'),
    path('payment/', paymentView, name='payment'),
    path('update-transactions/<subscription_id>/', updateTransaction, name='update-transactions' ), 
    path('profile/', profileView, name='profile'),
    path('cancel/', cancleSub, name="cancel")
]

src/Series/urls.py
from django.urls import path

from .views import SeriesListView, SeriesDetailView, EpisodesDetailView

app_name = 'Series'

urlpatterns = [
    path('', SeriesListView.as_view(), name='list_series'),
    path('<slug>', SeriesDetailView.as_view(), name='series_detail'),
    path('<series_slug>/<episode_slug>/', EpisodesDetailView.as_view(), name='episode_detail')
]

src/video_sub_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Series.urls', namespace='Series')),
    path('plans/', include('Plans.urls', namespace='Plans')),

]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/Series/models.py
from django.db import models
from django.urls import reverse


from Plans.models import Plans
# Create your models here.
class Series(models.Model):
	slug				= models.SlugField()
	title				= models.CharField(max_length=100)
	description			= models.TextField()
	allowed_plans		= models.ManyToManyField(Plans)


	def __str__(self):
		return self.title


	def get_absolute_url(self):
		return reverse('Series:series_detail', kwargs={'slug': self.slug})


	@property
	def episodes(self):
		return self.episodes_set.all().order_by("position")
	


	class Meta:
		verbose_name			= 'Series'
		verbose_name_plural		= 'Series'



class Episodes(models.Model):
	slug 				= models.SlugField()
	episode_title		= models.CharField(max_length=100)
	series 				= models.ForeignKey(Series, on_delete=models.SET_NULL, null=True)
	position			= models.IntegerField()
	video_url			= models.CharField(max_length=200)
	thumbnail			= models.ImageField()


	def __str__(self):
		return self.episode_title



	def get_absolute_url(self):
		return reverse('Series:episode_detail',
						kwargs={
								'series_slug': self.series.slug,
								'episode_slug': self.slug
						})		



	class Meta:
		verbose_name 			= 'Episode'
		verbose_name_plural		= 'Episodes'	

src/Series/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, View

from .models import Series, Episodes
from Plans.models import UserPlan
# Create your views here.



class SeriesListView(ListView):
	model 			= Series



class SeriesDetailView(DetailView):
	model 			= Series



class EpisodesDetailView(View):
	"""
		detialview for the episodes, it inherits from View, since 
		we intend for this view to be customizable
	"""

	def get(self, request, series_slug, episode_slug, *args, **kwargs):
		"""
			We will filter all the series be some slug,
			Then filter all the episodes from the series result by some slug
		"""

		templates 	= "Series/episode_detail.html"

		series_qs 	= Series.objects.filter(slug=series_slug)
		if series_qs.exists():
			series 	= series_qs.first()

		episode_qs 	= series.episodes.filter(slug=episode_slug)
		if episode_qs.exists():
			episode = episode_qs.first()


		#Check user plan_type
		user_plan 		= UserPlan.objects.filter(user=request.user).first()
		user_plan_type 	= user_plan.plan.plan_type

		#get allowed series for the given plan
		series_allowed_plan_type 	= series.allowed_plans.all()

		context						= {
					'episode_object': None
		}


		#check if user can view series
		if series_allowed_plan_type.filter(plan_type=user_plan_type).exists():
			context 	= {
					'episode_object': episode
			}

		return render(request, templates, context)

src/Series/templates/Series/episode_detail.html
{% extends 'base.html' %}

{% block post_detail_link %}
	{% if episode_object is not None %}
		<li><a href="{{episode_object.Series.get_absolute_url}} "> {{episode_object.Series.title}} </a></li>
		<li>{{episode_object.title}}</li>
	{% endif %}
{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-sm-4 col-mid-4">
				<h1>Episode Detail View</h1>

				{% if episode_object is not None %}
			 
			 		<h3>{{ episode_object.episode_title }}</h3>

			 		<video controls
			 				controlsList="nondownload"
			 				poster="{{episode_object.thumbnail.url}} "
			 				src="/static{{episode_object.video_url}} "
			 				width="300"
			 				height="200">
			 			
			 		</video>

			 	{% else %}
			 		<h3>upgrade plan</h3>
			 		<h4>To view Episode, upgrade Plan</h4>
			 		<a href="{% url 'Plans:plan_list' %}"><button class="btn btn-primary">Plans</button> </a>
				{% endif %}
			</div>
			
		</div>
		
	</div>

{% endblock %}

src/Series/templates/Series/series_detail.html
{% extends 'base.html' %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-sm-4 col-mid-4">
				<h1>Episodes </h1>
				<p><b>Series Title</b>: {{object.title}}</p>
				<p><b>About Series</b>: {{object.description}}</p>
				<p>{% for episode in object.episodes %}
					<ol>
						<li><a href="{{episode.get_absolute_url }}">{{episode.episode_title}}</a></li>
					</ol> 
					{% endfor %}
				</p>
			</div>
			
		</div>
		
	</div>

{% endblock %}

src/Series/templates/Series/series_list.html
{% extends 'base.html' %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-sm-4 col-mid-4">
				<h1>Series</h1>
				{% for obj in object_list %}
					<a href="{{ obj.get_absolute_url }}">{{ obj }}</a>
				{% endfor %}
				
			</div>
			
		</div>
		
	</div>

{% endblock %}